- name : deploiement poc mbc
  hosts: winhosts
  tasks:
    - name: add a new file
      win_file:
        path: C:\scripts\PSscript2.ps1
        state: touch
    - name: remove a folder
      win_file:
        path: C:\scripts\TestScripts
        state: absent
    - name: Download release
      get_url:
        url: https://github.com/enioka/mobicop/archive/32.10.zip
        dest: C:\scripts\TestScripts
