- name : deploiement poc mbc
  hosts: winhosts
  tasks:
    - name: add a new file
      win_file:
        path: C:\scripts\PSscript2.ps1
        state: touch
    - name: remove a folder
      win_file:
        path: C:\scripts\TestScripts
        state: absent
    - git:
        repo: 'https://github.com/enioka/mobicop.git'
        dest: C:\scripts\TestScripts
        version: release-32.10
